"""empty message

Revision ID: f1dc52a7cee4
Revises: 1f62a0cdf4f8
Create Date: 2023-07-31 15:01:49.446567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dc52a7cee4'
down_revision = '1f62a0cdf4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userInfo', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
